---
- name: to check the python
  raw: test -e /usr/bin/pip
  changed_when: false
  failed_when: false
  become: true
  register: check_pip

- name: to install the pip
  apt:
    pkg: ["python3-pip"]
    update_cache: no
    state: present
  become: true
  when: check_pip.rc == 1


- name: to install the pywinrm
  pip:
    name: ["pywinrm"]
  become: true

- name: setup the windows ansible directory
  file:
    path: /ansible-windows
    state: directory


- name: setup the windows ansible inventory directory
  file:
    path: /ansible-windows/inventory
    state: directory

- name: setup the windows ansible inventory group_vars
  file:
    path: /ansible-windows/inventory/group_vars
    state: directory

- name: setup the ansible configuration file
  template:
    src: templates/ansible.cfg.j2
    dest: /ansible-windows/ansible.cfg

- name: setup the windows ansible inventory file
  template:
    src: templates/winhosts
    dest: /ansible-windows/inventory/winhosts

- name: setup the windows ansible logging file
  file:
    path: /ansible-windows/windowsansible.log
    state: touch

- name: setup the windows group_vars file
  template:
    src: templates/all
    dest: /ansible-windows/inventory/group_vars/all
