# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: azselfpool
  vmImage: 'az-kg-win-agent'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
- powershell: "New-item -itemtype Directory c:\\testdir"
  displayName: "Create new directory step"
  name: "Directorycreation"
