---
- name: Sample playbook
  hosts: localhost
  tasks:
  - name: get the hostname
    debug:
      msg: Hello world!
  
  # - name: Setting-Windows-Ansible
  #   include_role:
  #     name: ansible-windows
