# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: azselfpool
  vmImage: 'az-kg-win-agent'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- powershell: Get-Service  | Where-Object {$_.DisplayName -like "Azure Pipelines Agent*"} | Select-Object DisplayName,Status
  displayName: "Single line pwsh script"
  name: PWSHinlinescript

- script: powershell $pwd
  displayName: Get the workdir 


- script: powershell try { cd pwsh } catch { write-host "no dir" }finally { ls }
  displayName: list the contents

- task: PowerShell@2
  inputs:
    filePath: 'pwsh\azuread\install-sync.ps1'
